name: Selenium Test Automation on Public Docker

on:
  push:
    branches:
      - feature_branch
      - main
  pull_request:
    branches:
      - feature_branch
      - main

jobs:
  test-execution:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444

      chrome-node:
        image: selenium/node-chrome:latest
        ports:
          - 5900:5900
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

      firefox-node:
        image: selenium/node-firefox:latest
        ports:
          - 5901:5900
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Wait for Selenium Grid to start
        run: |
          echo "Waiting for Selenium Grid..."
          sleep 15  # Wait for containers to be ready

      - name: Run tests on Selenium Grid
        run: mvn clean test -DsuiteXmlFile=testng.xml -Dbrowser=chrome -DexecutionMode=grid

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/
